In [9]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as im
import sympy as sp
from PIL import Image, ImageOps


In [103]:
i=0
#size of picture
imgdir = "12 LY\\" + "1.jpg"
im1= Image.open(imgdir)
im2=ImageOps.grayscale(im1)
A = im.pil_to_array(im2)
h, w = np.shape(A)

In [ ]:
#size of data

for i in range(32):
    imgdir = "12 LY\\" + str(i) + ".jpg"
#Nhap hinh anh
    im1 = Image.open(imgdir)
#Grayscale
    im2 = ImageOps.grayscale(im1)
#chuyen thanh mot ma tran ngang
    A = im.pil_to_array(im2)

    A = np.concatenate(A,axis=None)
    if i == 0:
        B = A
    else:
        B = np.column_stack((B,A))
print(B)

[[204 204 204 ... 204 204 204]
 [204 204 204 ... 204 204 204]
 [204 204 204 ... 204 204 204]
 ...
 [209 216 192 ... 222 216 213]
 [209 216 194 ... 222 214 213]
 [209 216 196 ... 222 214 213]]


In [131]:
C=np.mean(B, axis=1)
C= C[:, np.newaxis]
B-C

array([[  0.0625 ,   0.0625 ,   0.0625 , ...,   0.0625 ,   0.0625 ,
          0.0625 ],
       [  0.0625 ,   0.0625 ,   0.0625 , ...,   0.0625 ,   0.0625 ,
          0.0625 ],
       [  0.0625 ,   0.0625 ,   0.0625 , ...,   0.0625 ,   0.0625 ,
          0.0625 ],
       ...,
       [ -1.28125,   5.71875, -18.28125, ...,  11.71875,   5.71875,
          2.71875],
       [ -2.03125,   4.96875, -17.03125, ...,  10.96875,   2.96875,
          1.96875],
       [ -2.46875,   4.53125, -15.46875, ...,  10.53125,   2.53125,
          1.53125]])

In [132]:
Bmean=B  - C
V, S, Vt = np.linalg.svd(Bmean.T @ Bmean)
V
S_matrix=np.diag(S)
S_inv=np.linalg.inv(S_matrix)
Bmean @ Vt.T @ S_inv

array([[ 2.97692150e-10,  3.29586003e-09, -1.02735357e-10, ...,
        -3.07949690e-08,  7.25288187e-09,  2.67542425e-08],
       [ 2.97692150e-10,  3.29586003e-09, -1.02735357e-10, ...,
        -3.07949690e-08,  7.25288187e-09,  2.67542425e-08],
       [ 2.97692150e-10,  3.29586003e-09, -1.02735357e-10, ...,
        -3.07949690e-08,  7.25288187e-09,  2.67542425e-08],
       ...,
       [ 8.57554195e-08,  2.75475251e-07, -1.83556731e-08, ...,
         1.75988676e-06, -5.50757784e-06,  1.32660231e-06],
       [ 8.34895974e-08,  2.68005819e-07,  1.47943594e-08, ...,
         1.67738703e-06, -4.90884527e-06,  1.00192371e-06],
       [ 8.49572916e-08,  2.68840882e-07,  1.61747875e-08, ...,
         1.77945246e-06, -4.66234612e-06,  1.37421579e-06]])

In [99]:
Bmean @ U


array([[ 7.43904890e-02,  4.59800031e-01, -1.00675170e-02, ...,
        -2.08740152e-01,  4.25934603e-02, -4.94396191e-16],
       [ 7.43904890e-02,  4.59800031e-01, -1.00675170e-02, ...,
        -2.08740152e-01,  4.25934603e-02, -4.94396191e-16],
       [ 7.43904890e-02,  4.59800031e-01, -1.00675170e-02, ...,
        -2.08740152e-01,  4.25934603e-02, -4.94396191e-16],
       ...,
       [ 2.14294787e+01,  3.84311008e+01, -1.79875805e+00, ...,
         1.19291898e+01, -3.23439431e+01, -4.91496600e-13],
       [ 2.08632709e+01,  3.73890525e+01,  1.44976830e+00, ...,
         1.13699749e+01, -2.88278108e+01, -4.61152817e-13],
       [ 2.12300340e+01,  3.75055508e+01,  1.58504289e+00, ...,
         1.20618136e+01, -2.73802135e+01, -4.50132119e-13]])